😥 Fix a judgment error
Fix a judgment error.
And remove bot's sharing record.
😝

diff --git a/.github/workflows/update_contributors.yml b/.github/workflows/update_contributors.yml
--- a/.github/workflows/update_contributors.yml
+++ b/.github/workflows/update_contributors.yml
@@ -14,15 +14,19 @@ jobs:
 
       - name: 'Check and Update'
         run: |
-          curl https://api.github.com/repos/$GITHUB_REPOSITORY/contributors | grep login | sed 's#    "login": "##g' | sed 's#",##g' > contributors.new
-          if [ `diff contributors.new contributors` == 0 ]; then
-              echo "No new Contributors, no Push required"
+          curl https://api.github.com/repos/$GITHUB_REPOSITORY/contributors \
+            | grep login \
+            | sed 's#    "login": "##g' \
+            | sed 's#",##g' \
+            | sed "s#github-actions[bot]\n##g" \
+            > contributors
+          git config user.name 'github-actions'
+          git config user.email 'github-actions[bot]@users.noreply.github.com'
+          git add -A
+          if ! git diff-index --quiet HEAD; then
+            echo "New Contributors available, push now"
+            git commit -am "Update contributors"
+            git push
           else
-              echo "New Contributors available, push now"
-              mv -f contributors.new contributors
-              git config user.name 'github-actions[bot]'
-              git config user.email 'github-actions[bot]@users.noreply.github.com'
-              git add .
-              git commit -am "Update contributors"
-              git push
+              echo "No new Contributors, no Push required"
           fi
